import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./theme-provider";
import * as React from "react";
import Header from "@/components/Header";
import Provider from './storeProvider';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="modal-root"></div>
        <div id="popover-container"></div>
        
        <React.StrictMode>
          <Provider>
            <ThemeProvider>
              <Header></Header>
              {children}
              {modal}
              
            </ThemeProvider>
          </Provider>
        </React.StrictMode>
      </body>
    </html>
  );
}
